replicaCount: 1

image:
  repository: europe-west1-docker.pkg.dev/centryl-erp-123/repo/app-go-tokenize
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  port: 8081
  targetPort: 8080
